version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'mathapp'
      MYSQL_USER: 'mathapp_api'
      MYSQL_PASSWORD: 'password_mathapp_api'
      MYSQL_ROOT_PASSWORD: admin_password
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes: 
      # Windows compatible volume for linux adjust appropriately
      - ./db:/var/lib/mysql